### 2.2.1 创建Tensor

In [1]:
import torch

x = torch.empty(5, 3)   # 创建一个5×3的未初始化的`Tensor`
x

tensor([[7.3988e+31, 4.4849e+21, 2.7370e+20],
        [6.4640e-04, 1.9823e+29, 1.8810e+31],
        [4.4339e+27, 1.7975e+19, 6.9481e+22],
        [1.7743e+28, 2.0535e-19, 1.4226e-13],
        [1.8037e+28, 7.2296e+31, 3.2605e-12]])

In [2]:
x = torch.rand(5, 3)    # 创建一个5×3的随机初始化的`Tensor`
x

tensor([[0.3951, 0.6583, 0.4607],
        [0.8427, 0.5753, 0.3884],
        [0.6411, 0.9887, 0.7268],
        [0.6892, 0.2425, 0.5747],
        [0.3250, 0.2380, 0.7643]])

In [3]:
x = torch.zeros(5, 3, dtype=torch.long) # 创建一个5×3的long型全0的`Tensor`
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
x = torch.tensor([5, 5.3])  # 直接根据数据创建
x

tensor([5.0000, 5.3000])

In [5]:
# 根据现有的`Tensor`创建，默认重用输入`Tensor`的一些属性，例如数据类型
x = x.new_ones(5, 3, dtype=torch.float64)   # 返回的x默认具有相同的torch.dtype
print(x)

x = torch.randn_like(x)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.9781,  1.7032,  1.4038],
        [-2.2837,  0.6084,  2.4455],
        [ 1.6116, -0.4963, -1.2148],
        [-0.7958, -1.6141,  0.4639],
        [ 0.3047, -0.8630,  0.5120]], dtype=torch.float64)


In [6]:
# 通过`shape`或者`size()`来获取`Tensor`的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [7]:
# 创建全1张量
a = torch.ones(2, 2)
# 创建全0张量
b = torch.zeros(2, 3)
# 创建对角线为1，其他为0的张量
c = torch.eye(3, 4)
# 创建指定范围和步长的向量
d = torch.arange(1, 10, 2)
# 创建从开始到结束均匀分n份向量
e = torch.linspace(0, 10, 100)
# 均匀/标准分布
f = torch.rand(2, 2)
g = torch.randn(2, 2)
# 正态分布/均匀分布
h = torch.normal(0, 1, (2, 2))
print(a, b, end='\n\n')
print(c, d, end='\n\n')
print(e, f, end='\n\n')
print(g, h, end='\n\n')

tensor([[1., 1.],
        [1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]) tensor([1, 3, 5, 7, 9])

tensor([ 0.0000,  0.1010,  0.2020,  0.3030,  0.4040,  0.5051,  0.6061,  0.7071,
         0.8081,  0.9091,  1.0101,  1.1111,  1.2121,  1.3131,  1.4141,  1.5152,
         1.6162,  1.7172,  1.8182,  1.9192,  2.0202,  2.1212,  2.2222,  2.3232,
         2.4242,  2.5253,  2.6263,  2.7273,  2.8283,  2.9293,  3.0303,  3.1313,
         3.2323,  3.3333,  3.4343,  3.5354,  3.6364,  3.7374,  3.8384,  3.9394,
         4.0404,  4.1414,  4.2424,  4.3434,  4.4444,  4.5455,  4.6465,  4.7475,
         4.8485,  4.9495,  5.0505,  5.1515,  5.2525,  5.3535,  5.4545,  5.5556,
         5.6566,  5.7576,  5.8586,  5.9596,  6.0606,  6.1616,  6.2626,  6.3636,
         6.4646,  6.5657,  6.6667,  6.7677,  6.8687,  6.9697,  7.0707,  7.1717,
         7.2727,  7.3737,  7.4747,  7.5758,  7.6768,  7.7778,  7.8788,  7.9798,
         8.08

### 2.2.2 操作

In [8]:
x = torch.rand(5, 3)
y = torch.randn(5, 3)
x + y

tensor([[-0.1505,  1.9058,  0.9361],
        [-0.7356,  1.0195,  0.0900],
        [-0.4226, -1.3690, -1.0433],
        [ 0.2169, -1.1246, -0.2390],
        [-0.5515, -1.0224, -0.6020]])

In [9]:
torch.add(x, y)

tensor([[-0.1505,  1.9058,  0.9361],
        [-0.7356,  1.0195,  0.0900],
        [-0.4226, -1.3690, -1.0433],
        [ 0.2169, -1.1246, -0.2390],
        [-0.5515, -1.0224, -0.6020]])

In [10]:
# 就地操作，在原来y的基础上加x，add x to y
y.add_(x)
y

tensor([[-0.1505,  1.9058,  0.9361],
        [-0.7356,  1.0195,  0.0900],
        [-0.4226, -1.3690, -1.0433],
        [ 0.2169, -1.1246, -0.2390],
        [-0.5515, -1.0224, -0.6020]])

> `PyTorch`操作inplace版本都有后缀`_`，例如`x.copy_(y)`, `x.t_()`

- 索引

索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改

In [11]:
x = torch.arange(12).reshape(3, 4)
y = x[0]
y += 1  # 等价于：y.add_(1)
print(y)
print(x)

tensor([1, 2, 3, 4])
tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [12]:
# 其他索引方式
indices = torch.tensor([0, 2])
print(torch.index_select(x, 0, indices))
print(torch.index_select(x, 1, indices))

tensor([[ 1,  2,  3,  4],
        [ 8,  9, 10, 11]])
tensor([[ 1,  3],
        [ 4,  6],
        [ 8, 10]])


- 改变形状

  - `view()`返回新的`Tensor`与原`Tensor`虽然可能有不同的`size`，但是共享`data`。
  - `reshape()`也可以改变形状，但是此函数不能保证返回的是拷贝还是共享(数据内存连续时)
  - 可以先用`clone`创造一个副本然后再使用`view`

In [13]:
x = torch.arange(15).reshape(3, 5)
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[-1,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


> 使用`clone`时还有一个好处是会被记录在计算图中，即梯度回传到副本时也会被传到源`Tensor`

另外一个常用的函数就是`item()`，可以将一个标量`Tensor`转换成一个Python number

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.4541])
-1.4540530443191528


### 线性代数

In [15]:
x = torch.randint(10, (4, 4))
print(x)
# 对角元素之和
print(torch.trace(x))
# 对角线元素
print(torch.diag(x))
# 矩阵的上三角/下三角，可指定偏移量
print(torch.triu(x))
# 转置
print(x.T)

tensor([[1, 0, 9, 3],
        [2, 2, 8, 9],
        [2, 5, 9, 6],
        [9, 8, 7, 8]])
tensor(20)
tensor([1, 2, 9, 8])
tensor([[1, 0, 9, 3],
        [0, 2, 8, 9],
        [0, 0, 9, 6],
        [0, 0, 0, 8]])
tensor([[1, 2, 2, 9],
        [0, 2, 5, 8],
        [9, 8, 9, 7],
        [3, 9, 6, 8]])


### 2.2.3 广播机制

对两个形状不同的`Tensor`按元素运算时，可能会触发广播(broadcasting)机制：先适当复制元素使这两个`Tensor`形状相同后再按元素运算。

In [16]:
x = torch.arange(1, 3).view(2,)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([1, 2])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


### 2.2.4 运算的内存开销

索引不会开辟新内存，而像`y = x + y`会开新内存，然后`y`指向新内存。

python自带的`id`函数，输出变量内存地址。

In [17]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


如果指定结果到原来的`y`的内存，可以使用前面的索引来进行替换操作。如下，把`x + y`的结果通过`[:]`写进`y`对应的内存中。

In [18]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


还可以使用运算符全名函数中的`out`参数或者自加运算符`+=`(也即`add_()`)达到上述效果，例如`torch.add(x, y, oy=ut=y)`和`y += x`(`y.add_(x)`)

In [19]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)  # y += x, y.add_(x)
print(id(y) == id_before)

True


> 虽然`view()`返回的`Tensor`与源`Tensor`是共享`data`的，但是依然是一个新的`Tensor`(因为`Tensor`除了包含`data`外还包含一些其他属性)，两者`id(内存地址)`并不一致。

In [20]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = y.view(2)
id(y) == id(z)

False

### 2.25 `Tensor`和`Numpy`互相转换

很容易用`numpy()`和`from_numpy()`将`Tensor`和`Numpy`中的数据互相转换。需要注意的是：这两个函数所产生的`Tensor`和`Numpy()`中的数组共享相同的内存(所以他们之间转换很快)，改变其中一个时另一个会改变！

> 使用`torch.tensor()`转换时，进行数据拷贝，返回的`Tensor`和原来数据不再共享内存。

In [21]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)

b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


所有在CPU上`Tensor`(除了`CharTensor`)都支持与Numpy数组相互转换。

In [23]:
# torch.Tensor
c = torch.tensor(a)

a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### 2.2.6 `Tensor` on GPU

用方法`to()`可以将`Tensor`在CPU和GPU(需要硬件支持)支持相互移动

In [25]:
# 以下代码只有在`Pytorch GPU`版本上才会执行
x = torch.randint(10, (3, 4))
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 5,  4,  3,  1],
        [ 1,  7,  5,  3],
        [ 3, 10,  5,  9]], device='cuda:0')
tensor([[ 5.,  4.,  3.,  1.],
        [ 1.,  7.,  5.,  3.],
        [ 3., 10.,  5.,  9.]], dtype=torch.float64)
